export const FETCH_INVENTORY = "FETCH_INVENTORY";
export const FETCH_SALES = "FETCH_SALES";
export const FETCH_SALES_STATS = "FETCH_SALES_STATS"
export const FETCH_STAFFS = "FETCH_STAFFS"
export const FETCH_ROLES = "FETCH_ROLES"
export const FETCH_PERMISSIONS = "FETCH_ROLES"